[build]
  command = "npm run build:web"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  EXPO_PUBLIC_API_URL = "https://ecocidadetcc.netlify.app/api"

[[redirects]]
  from = "/api/*"
  to = "http://137.131.143.164:3000/:splat"
  status = 200
  force = true
