import { Ionicons } from "@expo/vector-icons";
import { useRouter } from "expo-router";
import React, { useEffect, useState } from "react";
import { ActivityIndicator, SafeAreaView, StatusBar, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { C, S } from "../constants/theme";
import { useToast } from "../context/toast-context";
import { getSupabaseSessionUser, isSupabaseConfigured, supabase } from "../services/supabase";

const cities=["Orlândia","Morro Agudo","Sales Oliveira","Nuporanga"];
export default function GoogleProfileScreen(){
 const router=useRouter(),toast=useToast();const[city,setCity]=useState(""),[loading,setLoading]=useState(false),[checking,setChecking]=useState(true);
 useEffect(()=>{let active=true;(async()=>{try{if(!isSupabaseConfigured()){router.replace("/login");return}const u=await getSupabaseSessionUser();if(!active)return;if(!u){router.replace("/login");return}if(u.city_id||u.city){router.replace("/map");return}}catch(e){console.error(e);router.replace("/login")}finally{if(active)setChecking(false)}})();return()=>{active=false}},[router]);
 const save=async()=>{if(!city){toast.addToast("Selecione sua cidade para continuar.","error");return}try{setLoading(true);if(!supabase)throw new Error("Supabase não configurado.");const{data:{user},error:ue}=await supabase.auth.getUser();if(ue)throw ue;if(!user)throw new Error("Sua sessão expirou. Faça login novamente.");const{data:c,error:ce}=await supabase.from("cities").select("id,name").eq("name",city).maybeSingle();if(ce)throw ce;if(!c)throw new Error("Cidade não encontrada.");const{error}=await supabase.from("profiles").upsert({id:user.id,name:user.user_metadata?.full_name||user.user_metadata?.name||user.email||"Usuário",email:user.email||"",role:"user",city:c.name,city_id:c.id,updated_at:new Date().toISOString()});if(error)throw error;router.replace("/map")}catch(e:any){console.error(e);toast.addToast(e?.message||"Não foi possível salvar sua cidade.","error")}finally{setLoading(false)}};
 if(checking)return <SafeAreaView style={styles.load}><StatusBar barStyle="dark-content"/><ActivityIndicator size="large" color={C.primary}/><Text style={styles.muted}>Verificando sua conta...</Text></SafeAreaView>;
 return <SafeAreaView style={styles.root}><StatusBar barStyle="dark-content"/><View style={styles.container}><View style={styles.icon}><Text style={styles.g}>G</Text></View><Text style={styles.title}>Quase tudo pronto!</Text><Text style={styles.subtitle}>Sua conta Google foi conectada. Agora selecione sua cidade para configurar o EcoCidade.</Text><Text style={styles.label}>SUA CIDADE</Text><View style={styles.list}>{cities.map(x=><TouchableOpacity key={x} disabled={loading} onPress={()=>setCity(x)} style={[styles.option,city===x&&styles.active]}><Text style={[styles.city,city===x&&styles.activeText]}>{x}</Text>{city===x&&<Ionicons name="checkmark-circle" size={22} color={C.primary}/>}</TouchableOpacity>)}</View><TouchableOpacity disabled={loading} onPress={save} style={[styles.button,loading&&styles.disabled]}>{loading?<ActivityIndicator color="white"/>:<><Text style={styles.buttonText}>Continuar</Text><Ionicons name="arrow-forward" size={20} color="white"/></>}</TouchableOpacity></View></SafeAreaView>
}
const styles=StyleSheet.create({root:{flex:1,backgroundColor:C.surface},load:{flex:1,backgroundColor:C.surface,justifyContent:"center",alignItems:"center"},muted:{marginTop:12,color:C.text2},container:{flex:1,padding:24,justifyContent:"center"},icon:{width:64,height:64,borderRadius:18,backgroundColor:C.surface2,borderWidth:1,borderColor:C.border,alignItems:"center",justifyContent:"center",alignSelf:"center",marginBottom:20},g:{fontSize:32,fontWeight:"800",color:C.primary},title:{fontSize:28,lineHeight:34,fontWeight:"800",color:C.text,textAlign:"center",marginBottom:10},subtitle:{fontSize:15,lineHeight:22,color:C.text2,textAlign:"center",marginBottom:32},label:{fontSize:12,fontWeight:"700",color:C.text3,letterSpacing:.5,marginBottom:10},list:{gap:10},option:{minHeight:54,paddingHorizontal:16,borderRadius:12,borderWidth:1.5,borderColor:C.border,backgroundColor:C.surface2,flexDirection:"row",alignItems:"center",justifyContent:"space-between"},active:{borderColor:C.primary,backgroundColor:"#eef5ff"},city:{color:C.text,fontSize:15,fontWeight:"600"},activeText:{color:C.primary},button:{marginTop:28,backgroundColor:C.primary,borderRadius:12,minHeight:52,paddingHorizontal:18,flexDirection:"row",alignItems:"center",justifyContent:"center",gap:8,...S.shadow.sm},disabled:{opacity:.7},buttonText:{color:"white",fontSize:15,fontWeight:"700"}});
